### ISSUE TITLE
Error: Unable to connect to gatsby-source-harperdb

### ISSUE THREAD

**Issue by sujoyduttajad** [atapas/flicks#1]
Hi, I'm facing this error after running `npm run develop` which says that it is unable to connect to gatsby-source-harperdb. please help me with the issue as I cannot proceed further if the DB is not working properly.

**Here's the gatsby-config file-**
```require('dotenv').config();

module.exports = {
  siteMetadata: {
    siteUrl: "https://www.yourdomain.tld",
    title: "book-library",
  },
  plugins: [
    "gatsby-plugin-sass",
    "gatsby-plugin-mdx",
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "pages",
        path: "./src/pages/",
      },
      __key: "pages",
    },
    {
      resolve: `gatsby-source-harperdb`,
      options: {
        secret: process.env.HARPER_DB_SECRET_KEY,
        url: process.env.HARPER_DB_URL,
        payload: {
          "operation": "sql",
          "sql":"SELECT * FROM library.book"
        },
        type: "books"
      },
    },
  ],
};

```

Below is the screenshot of the GraphQL directory where it is not showing any books/allBooks schema although I have declared it.
![Screenshot 2021-09-06 111811](https://user-images.githubusercontent.com/33634147/132166993-e03a2d36-2c7e-4621-a116-ee149089536d.png)

**Here's the error showing in my console-**
``` ERROR 

Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config: {
    url: 'undefined',
    method: 'post',
    data: '{"operation":"sql","sql":"SELECT * FROM library.book"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'Basic undefined',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 54
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: 'undefined',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: null,
      port: null,
      nativeProtocols: [Object],
      pathname: 'undefined'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 54,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST undefined HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Basic undefined\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 54\r\n' +
        'Host: localhost\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: 'undefined',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http:undefined',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}```

**Comment by atapas** [comment]
Hey @sujoyduttajad, Thanks for letting me know about the issue. I need a few more details to debug further and help you.

> please help me with the issue as I cannot proceed further if the DB is not working properly.

What do you mean the DB is not working properly? DB needs to be in working condition for the plugin to fetch the data. Are you able to query the harperDB tables directly?

**Comment by sujoyduttajad** [comment]
Sorry, my mistake it should have been the plugin. As per your blog I followed the instructions to setup the HarperDB that's working fine I double-checked the schema. HarperDB is working properly but the issue is with the plugin(gatsby-source-harperdb) which I think is not able to connect with the DB via the GraphQL. I'm new to GraphQL so correct me if I'm wrong but it looks like the plugin is causing the issue.

**Comment by atapas** [comment]
@sujoyduttajad , Thanks that's helpful.

Surprising. I just tested the graphQL part again with the plugin. It seems to be working fine. A sanity check,  you are on Gatsby version 2 or 3? Also with the error, it looks like port 80 is busy on your machine.

Here is my GraphQL output

![image](https://user-images.githubusercontent.com/3633137/132180245-ec58f6ea-56ec-4a33-8ac7-405b6c8a0bf4.png)

**Comment by sujoyduttajad** [comment]
Okay let me check pot 80 is busy I'm running a Next.js app

**Comment by sujoyduttajad** [comment]
Gatsby 3 but there are a lot of dependencies that I didn't downloaded - 
![image](https://user-images.githubusercontent.com/33634147/132184839-5e437dc7-97e0-4d73-8bc7-6aff0215bbfa.png)

**Comment by atapas** [comment]
> Okay let me check pot 80 is busy I'm running a Next.js app

Sure, let me know...

**Comment by atapas** [comment]
> Gatsby 3 but there are a lot of dependencies that I didn't downloaded -
> ![image](https://user-images.githubusercontent.com/33634147/132184839-5e437dc7-97e0-4d73-8bc7-6aff0215bbfa.png)

You need the gatsby-source-harperdb plugin.

**Comment by sujoyduttajad** [comment]
Yes I included it

**Comment by sujoyduttajad** [comment]
I checked port 80 is clear, stopped all other apps still the same issue. I might be missing some steps. Did you check my config file?

**Comment by atapas** [comment]
@sujoyduttajad, Your config looks good to me.

Apart from the port thing I suspected before, what I see is this in the error.

```shell
 config: {
    url: 'undefined',
```

Why the `url` is going as `undefined`. If you are using `axios` to make a call and do not pass the URL or protocol, it throws the exact same error you get(the error message is a bit vague: https://github.com/axios/axios/issues/3593).

Could you please confirm why the URL is going undefined?

**Comment by sujoyduttajad** [comment]
Okay let me check, I'm not using Axios but thanks for the tip

**Comment by sujoyduttajad** [comment]
Is it because of the siteURL - 
![image](https://user-images.githubusercontent.com/33634147/132207247-9afd9115-8e37-4363-a0c8-b47edcdb9db5.png)

I guess this is for hosting purposes right?

**Comment by atapas** [comment]
> Is it because of the siteURL -
> ![image](https://user-images.githubusercontent.com/33634147/132207247-9afd9115-8e37-4363-a0c8-b47edcdb9db5.png)

NO.

> I guess this is for hosting purposes right?

It is for the SEO purpose.

**Comment by atapas** [comment]
> Okay let me check, I'm not using Axios but thanks for the tip

Sure @sujoyduttajad , if required we can catch up for a LIVE Debugging sometime this week to resolve it :) I'm all for it.

Feel free to share your repo with me in the advance! Have a good day.

**Comment by sujoyduttajad** [comment]
Okay thanks, @atapas for looking through the issue. Sure we can catch up this weekend. 
Sure here's my repo - [https://github.com/sujoyduttajad/Gatsby-book-library](https://github.com/sujoyduttajad/Gatsby-book-library)

**Comment by sujoyduttajad** [comment]
Thanks, Tapas for the interaction btw the error is fixed that after debugging we found the .env file should technically be present in the same root level as the src, my mistake.
